#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XCalc.Resource", IsApplication=true)]

namespace XCalc
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "12.1.0.11")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public const int alignmentMode = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int columnCount = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int columnOrderPreserved = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int font = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int fontProviderAuthority = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int fontProviderCerts = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int fontProviderFetchStrategy = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int fontProviderFetchTimeout = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int fontProviderPackage = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int fontProviderQuery = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int fontStyle = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int fontWeight = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int layout_column = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int layout_columnSpan = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int layout_columnWeight = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public const int layout_gravity = 2130771983;
			
			// aapt resource value: 0x7F010010
			public const int layout_row = 2130771984;
			
			// aapt resource value: 0x7F010011
			public const int layout_rowSpan = 2130771985;
			
			// aapt resource value: 0x7F010012
			public const int layout_rowWeight = 2130771986;
			
			// aapt resource value: 0x7F010013
			public const int orientation = 2130771987;
			
			// aapt resource value: 0x7F010014
			public const int rowCount = 2130771988;
			
			// aapt resource value: 0x7F010015
			public const int rowOrderPreserved = 2130771989;
			
			// aapt resource value: 0x7F010016
			public const int useDefaultMargins = 2130771990;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7F020000
			public const int abc_action_bar_embed_tabs = 2130837504;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F030000
			public const int notification_action_color_filter = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int notification_icon_bg_color = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int ripple_material_light = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int secondary_text_default_material_light = 2130903043;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F040000
			public const int compat_button_inset_horizontal_material = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int compat_button_inset_vertical_material = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int compat_button_padding_horizontal_material = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int compat_button_padding_vertical_material = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int compat_control_corner_material = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int default_gap = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int notification_action_icon_size = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int notification_action_text_size = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int notification_big_circle_margin = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int notification_content_margin_start = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int notification_large_icon_height = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int notification_large_icon_width = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int notification_main_column_padding_top = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int notification_media_narrow_margin = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int notification_right_icon_size = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int notification_right_side_padding_top = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int notification_small_icon_background_padding = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int notification_small_icon_size_as_large = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int notification_subtext_size = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int notification_top_pad = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int notification_top_pad_large_text = 2130968596;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F050000
			public const int notification_action_background = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int notification_bg = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int notification_bg_low = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int notification_bg_low_normal = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int notification_bg_low_pressed = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int notification_bg_normal = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int notification_bg_normal_pressed = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int notification_icon_background = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int notification_template_icon_bg = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int notification_template_icon_low_bg = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int notification_tile_bg = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int notify_panel_notification_icon_bg = 2131034123;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F060004
			public const int actions = 2131099652;
			
			// aapt resource value: 0x7F060000
			public const int action_container = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int action_divider = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int action_image = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int action_text = 2131099651;
			
			// aapt resource value: 0x7F060005
			public const int alignBounds = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int alignMargins = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int async = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int blocking = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int bottom = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int calculator_text_view = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int center = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int center_horizontal = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int center_vertical = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int chronometer = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int clip_horizontal = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int clip_vertical = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int end = 2131099665;
			
			// aapt resource value: 0x7F060012
			public const int fill = 2131099666;
			
			// aapt resource value: 0x7F060013
			public const int fill_horizontal = 2131099667;
			
			// aapt resource value: 0x7F060014
			public const int fill_vertical = 2131099668;
			
			// aapt resource value: 0x7F060015
			public const int forever = 2131099669;
			
			// aapt resource value: 0x7F060016
			public const int horizontal = 2131099670;
			
			// aapt resource value: 0x7F060017
			public const int icon = 2131099671;
			
			// aapt resource value: 0x7F060018
			public const int icon_group = 2131099672;
			
			// aapt resource value: 0x7F060019
			public const int info = 2131099673;
			
			// aapt resource value: 0x7F06001A
			public const int italic = 2131099674;
			
			// aapt resource value: 0x7F06001B
			public const int left = 2131099675;
			
			// aapt resource value: 0x7F06001C
			public const int line1 = 2131099676;
			
			// aapt resource value: 0x7F06001D
			public const int line3 = 2131099677;
			
			// aapt resource value: 0x7F06001E
			public const int normal = 2131099678;
			
			// aapt resource value: 0x7F06001F
			public const int notification_background = 2131099679;
			
			// aapt resource value: 0x7F060020
			public const int notification_main_column = 2131099680;
			
			// aapt resource value: 0x7F060021
			public const int notification_main_column_container = 2131099681;
			
			// aapt resource value: 0x7F060022
			public const int right = 2131099682;
			
			// aapt resource value: 0x7F060023
			public const int right_icon = 2131099683;
			
			// aapt resource value: 0x7F060024
			public const int right_side = 2131099684;
			
			// aapt resource value: 0x7F060025
			public const int start = 2131099685;
			
			// aapt resource value: 0x7F060026
			public const int text = 2131099686;
			
			// aapt resource value: 0x7F060027
			public const int text2 = 2131099687;
			
			// aapt resource value: 0x7F060028
			public const int time = 2131099688;
			
			// aapt resource value: 0x7F060029
			public const int title = 2131099689;
			
			// aapt resource value: 0x7F06002A
			public const int top = 2131099690;
			
			// aapt resource value: 0x7F06002B
			public const int vertical = 2131099691;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F070000
			public const int status_bar_notification_info_maxnum = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F080000
			public const int Main = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int notification_action = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int notification_action_tombstone = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int notification_template_custom_big = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int notification_template_icon_group = 2131230724;
			
			// aapt resource value: 0x7F080005
			public const int notification_template_part_chronometer = 2131230725;
			
			// aapt resource value: 0x7F080006
			public const int notification_template_part_time = 2131230726;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F090000
			public const int app_name = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int status_bar_notification_info_overflow = 2131296257;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0A0007
			public const int button_calculator = 2131361799;
			
			// aapt resource value: 0x7F0A0000
			public const int TextAppearance_Compat_Notification = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int TextAppearance_Compat_Notification_Info = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int TextAppearance_Compat_Notification_Line2 = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public const int TextAppearance_Compat_Notification_Time = 2131361795;
			
			// aapt resource value: 0x7F0A0004
			public const int TextAppearance_Compat_Notification_Title = 2131361796;
			
			// aapt resource value: 0x7F0A0005
			public const int Widget_Compat_NotificationActionContainer = 2131361797;
			
			// aapt resource value: 0x7F0A0006
			public const int Widget_Compat_NotificationActionText = 2131361798;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F010004,0x7F010005,0x7F010006,0x7F010007,0x7F010008,0x7F010009 }
			public static int[] FontFamily = new int[] {
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: { 0x7F010003,0x7F01000A,0x7F01000B }
			public static int[] FontFamilyFont = new int[] {
					2130771971,
					2130771978,
					2130771979};
			
			// aapt resource value: 0
			public const int FontFamilyFont_font = 0;
			
			// aapt resource value: 1
			public const int FontFamilyFont_fontStyle = 1;
			
			// aapt resource value: 2
			public const int FontFamilyFont_fontWeight = 2;
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderQuery = 5;
			
			// aapt resource value: { 0x7F010000,0x7F010001,0x7F010002,0x7F010013,0x7F010014,0x7F010015,0x7F010016 }
			public static int[] GridLayout = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771987,
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 0
			public const int GridLayout_alignmentMode = 0;
			
			// aapt resource value: 1
			public const int GridLayout_columnCount = 1;
			
			// aapt resource value: 2
			public const int GridLayout_columnOrderPreserved = 2;
			
			// aapt resource value: { 0x10100F4,0x10100F5,0x10100F6,0x10100F7,0x10100F8,0x10100F9,0x10100FA,0x7F01000C,0x7F01000D,0x7F01000E,0x7F01000F,0x7F010010,0x7F010011,0x7F010012 }
			public static int[] GridLayout_Layout = new int[] {
					16842996,
					16842997,
					16842998,
					16842999,
					16843000,
					16843001,
					16843002,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986};
			
			// aapt resource value: 1
			public const int GridLayout_Layout_android_layout_height = 1;
			
			// aapt resource value: 2
			public const int GridLayout_Layout_android_layout_margin = 2;
			
			// aapt resource value: 6
			public const int GridLayout_Layout_android_layout_marginBottom = 6;
			
			// aapt resource value: 3
			public const int GridLayout_Layout_android_layout_marginLeft = 3;
			
			// aapt resource value: 5
			public const int GridLayout_Layout_android_layout_marginRight = 5;
			
			// aapt resource value: 4
			public const int GridLayout_Layout_android_layout_marginTop = 4;
			
			// aapt resource value: 0
			public const int GridLayout_Layout_android_layout_width = 0;
			
			// aapt resource value: 7
			public const int GridLayout_Layout_layout_column = 7;
			
			// aapt resource value: 8
			public const int GridLayout_Layout_layout_columnSpan = 8;
			
			// aapt resource value: 9
			public const int GridLayout_Layout_layout_columnWeight = 9;
			
			// aapt resource value: 10
			public const int GridLayout_Layout_layout_gravity = 10;
			
			// aapt resource value: 11
			public const int GridLayout_Layout_layout_row = 11;
			
			// aapt resource value: 12
			public const int GridLayout_Layout_layout_rowSpan = 12;
			
			// aapt resource value: 13
			public const int GridLayout_Layout_layout_rowWeight = 13;
			
			// aapt resource value: 3
			public const int GridLayout_orientation = 3;
			
			// aapt resource value: 4
			public const int GridLayout_rowCount = 4;
			
			// aapt resource value: 5
			public const int GridLayout_rowOrderPreserved = 5;
			
			// aapt resource value: 6
			public const int GridLayout_useDefaultMargins = 6;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
